version: "3"
services:
    web:
        build: .
        ports:
            - "80:80"
        restart: always
        env_file:
            - .env
        volumes:
            #volume now binds entire folder
            - .:/myportfolio
        depends_on:
            - db
            # start db container before web

    db:
        image: postgres
        restart: always
        env_file:
            - .env
