version: '3'
services:
	web: 
		build: . 
		ports: 
			- "5000:5000"
		volumes: 
			- "/usercode/:/code"
		# Link database container to app container
		# in the bridge network we have to specify which container should be accessible to which
		links: 
			- "database:backenddb"
	
	database:
		image: mysql/mysql-server:5.7
		environment: 
			- "MYSQL_ROOT_PASSWORD=root"
			- "MYSQL_USER=testuser"
			- "MYSQL_PASSWORD=admin123"
			- "MYSQL_DATABASE=backend"
		# Mount init.sql file will automatically run and create table
		# Eerything in docker-entrypoint-initdb.d folder is executed when container starts 
		volumes: 
			- "/usercode/db/init.sql:/docker-entrypoint-initdb.d/init.sql"