name: Deploy

on:
  push:
    branches:
      - master
    workflow_dispatch:

jobs:
  deploy:
    name: "Deploy to AWS EC2 VM"
    runs-on: ubuntu-latest
    steps:
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          git config --global user.name "PurpleUltralisk"
          git config --global user.email $GH_EMAIL
          echo "$RSA_KEY" > ~/.ssh/id_rsa
          sudo chmod 600 ~/.ssh/id_rsa
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/deploy-key.pem
          sudo chmod 600 ~/.ssh/deploy-key.pem
          cat >> ~/.ssh/config <<END
          Host my-vm
            HostName $SSH_IP
            User $SSH_USER
            IdentityFile ~/.ssh/deploy-key.pem
            StrictHostKeyChecking no
          END
        env:
          RSA_KEY: ${{ secrets.RSA_KEY }}
          GH_EMAIL: ${{ secrets.GH_EMAIL }}
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_IP: ${{ secrets.SSH_IP }}
      
      - name: Test git config
        run: git config user.name
      
      - name: Test github connection
        run: ssh -T git@github.com
      
      - name: Deploy site 
        run: ssh my-vm 'cd ${{ secrets.PROJECT_ROOT }} && git fetch && git rest --hard origin/master && docker-compose up -d --build'